AWSTemplateFormatVersion: 2010-09-09
Description: QnABot on AWS LLM Plugin for Anthropic - v0.1.0
   
Parameters:
  APIKey:
    Type: String
    Description: Anthropic API Key (stored in Secrets Manager - see stack Outputs)
    Default: ''
    NoEcho: true

  LLMModelId:
    Type: String
    Default: claude-instant-1
    AllowedValues: # to update list of available models
      - claude-instant-1
      - claude-1
    Description: Anthropic LLM Model

Resources:
  ApiKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: API Key
      Name: !Ref AWS::StackName
      SecretString: !Ref APIKey

  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'secretsmanager:GetResourcePolicy'
                  - 'secretsmanager:GetSecretValue'
                  - 'secretsmanager:DescribeSecret'
                  - 'secretsmanager:ListSecretVersionIds'
                Resource: !Ref ApiKeySecret
          PolicyName: SecretsManagerPolicy

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: "llm.lambda_handler"
      Role: !GetAtt 'LambdaFunctionRole.Arn'
      MemorySize: 128
      Timeout: 60
      Runtime: python3.10       
      Environment:
        Variables:
          API_KEY_SECRET_NAME: !Ref AWS::StackName
      Code: ./src

  OutputSettingsFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  
  OutputSettingsFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: settings.lambda_handler
      Role: !GetAtt 'OutputSettingsFunctionRole.Arn'
      Runtime: python3.10
      Timeout: 10
      MemorySize: 128
      Code: ./src

  OutputSettings:
    Type: Custom::OutputSettings
    Properties:
      ServiceToken: !GetAtt OutputSettingsFunction.Arn
      ModelId: !Ref LLMModelId

Outputs:
  APIKeySecret:
    Description: Link to Secrets Manager console to input API Key
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/secretsmanager/secret?region=${AWS::Region}&name=${AWS::StackName}"
    
  LLMLambdaArn:
    Description: Lambda function ARN (use for QnABot param "LLMLambdaArn")
    Value: !GetAtt LambdaFunction.Arn

  QnABotSettingGenerateQueryPromptTemplate:
    Description: QnABot Designer Setting "LLM_GENERATE_QUERY_PROMPT_TEMPLATE"
    Value: !GetAtt OutputSettings.LLM_GENERATE_QUERY_PROMPT_TEMPLATE

  QnABotSettingGenerateQueryModelParams:
    Description: QnABot Designer Setting "LLM_GENERATE_QUERY_MODEL_PARAMS"
    Value: !GetAtt OutputSettings.LLM_GENERATE_QUERY_MODEL_PARAMS

  QnABotSettingQAPromptTemplate:
    Description: QnABot Designer Setting "LLM_QA_PROMPT_TEMPLATE"
    Value: !GetAtt OutputSettings.LLM_QA_PROMPT_TEMPLATE

  QnABotSettingQAModelParams:
    Description: QnABot Designer Setting "LLM_QA_MODEL_PARAMS"
    Value: !GetAtt OutputSettings.LLM_QA_MODEL_PARAMS